# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-29 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0007_auto_20180309_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_level',
            name='totallevel',
            field=models.IntegerField(default=100),
        ),
    ]
